# Describes the format for available huesync services

set_sync_state:
  name: Set sync state
  description: Control the complete sync state of the Philips Hue Play HDMI Syncbox. This is an advanced service and contains potential conflicting fields. Use responsibly!
  target:
    entity:
      integration: huesyncbox
      domain: media_player
  fields:
    sync:
      name: Sync
      description: Set sync state on or off.
      example: true
      selector:
        boolean:
    sync_toggle:
      name: Sync toggle
      description: Toggle sync state between on/off.
      example: true
      selector:
        boolean:
    brightness:
      name: Brightness
      description: Brightness value to set [0,1].
      example: 0.42
      selector:
        number:
          min: 0.0
          max: 1.0
          step: 0.01
          mode: slider
    brightness_step:
      name: Brightness step
      description: Change brightness relative to the current state. Should be between -1..1.
      example: -0.2
      selector:
        number:
          min: -1.0
          max: 1.0
          step: 0.01
          mode: slider
    mode:
      name: Mode
      description: Mode to set. One of 'video', 'music', 'game'.
      example: video
      selector:
        select:
          options:
            - video
            - music
            - game
    mode_next:
      name: Next mode
      description: Select next mode, will wrap around.
      example: true
      selector:
        boolean:
    mode_prev:
      name: Previous mode
      description: Select previous mode, will wrap around.
      example: true
      selector:
        boolean:
    intensity:
      name: Intensity
      description: Intensity to set. One of 'subtle', 'moderate', 'high', 'intense'.
      example: high
      selector:
        select:
          options:
            - subtle
            - moderate
            - high
            - intense
    intensity_next:
      name: Next intensity
      description: Select next intensity.
      example: true
      selector:
        boolean:
    intensity_prev:
      name: Previous intensity
      description: Select previous intensity.
      example: true
      selector:
        boolean:
    input:
      name: Input
      description: Input to select. One of 'input1', 'input2', 'input3', 'input4'.
      example: input1
      selector:
        select:
          options:
            - input1
            - input2
            - input3
            - input4
    input_next:
      name: Next input
      description: Select next input, wraps around.
      example: true
      selector:
        boolean:
    input_prev:
      name: Previous input
      description: Select previous input, wraps around.
      example: true
      selector:
        boolean:
    entertainment_area:
      name: Entertainment area
      description: Entertainment area to select. Can be one of the names available in 'entertainment_area_list' attribute.
      example: TV Area
      selector:
        text:

set_brightness:
  name: Set brightness
  description: Set brightness for the Philips Hue Play HDMI Syncbox.
  target:
    entity:
      integration: huesyncbox
      domain: media_player
  fields:
    brightness:
      name: Brightness
      description: Brightness value to set [0,1].
      example: 0.42
      required: true
      selector:
        number:
          min: 0.0
          max: 1.0
          step: 0.01
          mode: slider

set_sync_mode:
  name: Set sync mode
  description: Set syncmode for the Philips Hue Play HDMI Syncbox.
  target:
    entity:
      integration: huesyncbox
      domain: media_player
  fields:
    mode:
      name: Mode
      description: Mode to set. One of 'video', 'music', 'game'.
      example: video
      required: true
      selector:
        select:
          options:
            - video
            - music
            - game

set_intensity:
  name: Set intensity
  description: Set intensity for the Philips Hue Play HDMI Syncbox.
  target:
    entity:
      integration: huesyncbox
      domain: media_player
  fields:
    intensity:
      name: Intensity
      description: Intensity to set. One of 'subtle', 'moderate', 'high', 'intense'.
      example: high
      required: true
      selector:
        select:
          options:
            - subtle
            - moderate
            - high
            - intense
    mode:
      name: Mode
      description: Optional mode to apply intensity to. If not set intensity is applied to current/last used mode.
      example: video
      selector:
        select:
          options:
            - video
            - music
            - game

set_entertainment_area:
  name: Select entertainment area
  description: Set entertainment area to be used for the Philips Hue Play HDMI Syncbox.
  target:
    entity:
      integration: huesyncbox
      domain: media_player
  fields:
    entertainment_area:
      name: Entertainment area
      description: Entertainment area to select. Must be one of the names available in 'entertainment_area_list' attribute.
      example: TV Area
      required: true
      selector:
        text:
